# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-09-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('hash_value', models.CharField(max_length=255)),
            ],
        ),
    ]
