# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-09-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_app', '0002_musics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
